AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TableName:
    Type: String
Resources:
  PersonsDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      -
        AttributeName: id
        AttributeType: S
      -
        AttributeName: name
        AttributeType: S
      KeySchema:
      -
        AttributeName: id
        KeyType: HASH
      -
        AttributeName: name
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: id-name
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Name
          ProjectionType: INCLUDE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref TableName
