service: application-dynamodb-stack

provider:
  name: aws
  runtime: java8
  region: us-east-1
  role: arn:aws:iam::132698621221:role/Administrator
  timeout: 30

resources:
  Resources:
    AppStore:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: applications
        AttributeDefinitions:
        -
          AttributeName: company_id
          AttributeType: S
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: updated
          AttributeType: S
        -
          AttributeName: itunesstore_id
          AttributeType: S
        KeySchema:
        -
          AttributeName: company_id
          KeyType: HASH
        -
          AttributeName: id
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
        -
          IndexName: company_id_updated-index
          KeySchema:
          -
            AttributeName: company_id
            KeyType: HASH
          -
            AttributeName: updated
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        -
          IndexName: company_id-index
          KeySchema:
          -
            AttributeName: company_id
            KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        -
          IndexName: company_id_itunesstore_id-index
          KeySchema:
          -
            AttributeName: company_id
            KeyType: HASH
          -
            AttributeName: itunesstore_id
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
