service: account  -dynamodb-stack

provider:
  name: aws
  runtime: java8
  region: us-east-1
  role: arn:aws:iam::132698621221:role/Administrator
  timeout: 30

resources:
  Resources:
    AccountsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
        -
          AttributeName: person_id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
        KeySchema:
        -
          AttributeName: person_id
          KeyType: HASH
        -
          AttributeName: email
          KeyType: RANGE
        LocalSecondaryIndexes:
        - IndexName: person_id-email
          KeySchema:
          - AttributeName: person_id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
          Projection:
            NonKeyAttributes:
            - Name
            ProjectionType: INCLUDE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: accounts
